### ISSUE TITLE
backwards colors, king/queen

### ISSUE THREAD

**Issue by wrigjl** [Tagada14/Chess#2]
There should be a white square on the bottom right (its dark in the UI). You have followed the rule of the queen goes on her own color, but because the squares are reversed, the king and queen are on the wrong squares. 

normal layout is:
```
rnbqkbnr
pppppppp
--------
--------
--------
--------
PPPPPPPP
RNBQKBNR
```

**Comment by Tagada14** [comment]
Thank you for pointing it out!
It's fixed now.
